const MOVIES_RAW = [
  { title: "Copland", year: 1997, director: "James Mangold" },
  { title: "Michael Clayton", year: 2007, director: "Tony Gilroy" },
  { title: "Hell or High Water", year: 2016, director: "David Mackenzie" },
  { title: "Sicario", year: 2015, director: "Denis Villeneuve" },
  { title: "Sicario: Day of the Soldado", year: 2018, director: "Stefano Sollima" },
  { title: "Major League", year: 1989, director: "David S. Ward" },
  { title: "Casablanca", year: 1942, director: "Michael Curtiz" },
  { title: "Forrest Gump", year: 1994, director: "Robert Zemeckis" },
  { title: "Big", year: 1988, director: "Penny Marshall" },
  { title: "Cast Away", year: 2000, director: "Robert Zemeckis" },
  { title: "Midnight Run", year: 1988, director: "Martin Brest" },
  { title: "Casino", year: 1995, director: "Martin Scorsese" },
  { title: "GoodFellas", year: 1990, director: "Martin Scorsese" },
  { title: "The Godfather", year: 1972, director: "Francis Ford Coppola" },
  { title: "The Godfather Part II", year: 1974, director: "Francis Ford Coppola" },
  { title: "Marathon Man", year: 1976, director: "John Schlesinger" },
  { title: "Meet the Parents", year: 2000, director: "Jay Roach" },
  { title: "The Equalizer", year: 2014, director: "Antoine Fuqua" },
  { title: "Man on Fire", year: 2004, director: "Tony Scott" },
  { title: "Mystic River", year: 2003, director: "Clint Eastwood" },
  { title: "The Town", year: 2010, director: "Ben Affleck" },
  { title: "Gone Baby Gone", year: 2007, director: "Ben Affleck" },
  { title: "The Departed", year: 2006, director: "Martin Scorsese" },
  { title: "Ace Ventura: Pet Detective", year: 1994, director: "Tom Shadyac" },
  { title: "Dumb and Dumber", year: 1994, director: "Peter Farrelly" },
  { title: "Rushmore", year: 1998, director: "Wes Anderson" },
  { title: "The Royal Tenenbaums", year: 2001, director: "Wes Anderson" },
  { title: "Clockers", year: 1995, director: "Spike Lee" },
  { title: "25th Hour", year: 2002, director: "Spike Lee" },
  { title: "Malcolm X", year: 1992, director: "Spike Lee" },
  { title: "The Fugitive", year: 1993, director: "Andrew Davis" },
  { title: "Raiders of the Lost Ark", year: 1981, director: "Steven Spielberg" },
  { title: "Indiana Jones and the Last Crusade", year: 1989, director: "Steven Spielberg" },
  { title: "Star Wars: A New Hope", year: 1977, director: "George Lucas" },
  { title: "The Empire Strikes Back", year: 1980, director: "Irvin Kershner" },
  { title: "Rocky", year: 1976, director: "John G. Avildsen" },
  { title: "Creed", year: 2015, director: "Ryan Coogler" },
  { title: "The Terminator", year: 1984, director: "James Cameron" },
  { title: "Terminator 2: Judgment Day", year: 1991, director: "James Cameron" },
  { title: "Kindergarten Cop", year: 1990, director: "Ivan Reitman" },
  { title: "First Blood", year: 1982, director: "Ted Kotcheff" },
  { title: "Witness", year: 1985, director: "Peter Weir" },
  { title: "JFK", year: 1991, director: "Oliver Stone" },
  { title: "The Shawshank Redemption", year: 1994, director: "Frank Darabont" },
  { title: "Pulp Fiction", year: 1994, director: "Quentin Tarantino" },
  { title: "Jackie Brown", year: 1997, director: "Quentin Tarantino" },
  { title: "Reservoir Dogs", year: 1992, director: "Quentin Tarantino" },
  { title: "Batman Begins", year: 2005, director: "Christopher Nolan" },
  { title: "The Dark Knight", year: 2008, director: "Christopher Nolan" },
  { title: "The Dark Knight Rises", year: 2012, director: "Christopher Nolan" },
  { title: "Oppenheimer", year: 2023, director: "Christopher Nolan" },
  { title: "Insomnia", year: 2002, director: "Christopher Nolan" },
  { title: "The Usual Suspects", year: 1995, director: "Bryan Singer" },
  { title: "Ronin", year: 1998, director: "John Frankenheimer" },
  { title: "The Last Samurai", year: 2003, director: "Edward Zwick" },
  { title: "Heat", year: 1995, director: "Michael Mann" },
  { title: "Collateral", year: 2004, director: "Michael Mann" },
  { title: "The Insider", year: 1999, director: "Michael Mann" },
  { title: "The Last of the Mohicans", year: 1992, director: "Michael Mann" },
  { title: "Thief", year: 1981, director: "Michael Mann" },
  { title: "The Silence of the Lambs", year: 1991, director: "Jonathan Demme" },
  { title: "The Karate Kid", year: 1984, director: "John G. Avildsen" },
  { title: "Gladiator", year: 2000, director: "Ridley Scott" },
  { title: "Dances with Wolves", year: 1990, director: "Kevin Costner" },
  { title: "Point Break", year: 1991, director: "Kathryn Bigelow" },
  { title: "Road House", year: 1989, director: "Rowdy Herrington" },
  { title: "The Conversation", year: 1974, director: "Francis Ford Coppola" },
  { title: "48 Hrs.", year: 1982, director: "Walter Hill" },
  { title: "Trading Places", year: 1983, director: "John Landis" },
  { title: "Coming to America", year: 1988, director: "John Landis" },
  { title: "Beverly Hills Cop", year: 1984, director: "Martin Brest" },
  { title: "Field of Dreams", year: 1989, director: "Phil Alden Robinson" },
  { title: "Hoop Dreams", year: 1994, director: "Steve James" },
  { title: "The Last Waltz", year: 1978, director: "Martin Scorsese" },
  { title: "Training Day", year: 2001, director: "Antoine Fuqua" },
  { title: "Taken", year: 2008, director: "Pierre Morel" },
  { title: "Blood Diamond", year: 2006, director: "Edward Zwick" },
  { title: "American History X", year: 1998, director: "Tony Kaye" },
  { title: "Rounders", year: 1998, director: "John Dahl" },
  { title: "Platoon", year: 1986, director: "Oliver Stone" },
  { title: "Lethal Weapon", year: 1987, director: "Richard Donner" },
  { title: "Lethal Weapon 2", year: 1989, director: "Richard Donner" },
  { title: "Planes, Trains and Automobiles", year: 1987, director: "John Hughes" },
  { title: "Uncle Buck", year: 1989, director: "John Hughes" },
  { title: "Braveheart", year: 1995, director: "Mel Gibson" },
  { title: "Dirty Rotten Scoundrels", year: 1988, director: "Frank Oz" },
  { title: "Sneakers", year: 1992, director: "Phil Alden Robinson" },
  { title: "A Few Good Men", year: 1992, director: "Rob Reiner" },
  { title: "All the President's Men", year: 1976, director: "Alan J. Pakula" },
  { title: "Cool Hand Luke", year: 1967, director: "Stuart Rosenberg" },
  { title: "Butch Cassidy and the Sundance Kid", year: 1969, director: "George Roy Hill" },
  { title: "The Hustler", year: 1961, director: "Robert Rossen" },
  { title: "Crimson Tide", year: 1995, director: "Tony Scott" },
  { title: "Out of Sight", year: 1998, director: "Steven Soderbergh" },
  { title: "Traffic", year: 2000, director: "Steven Soderbergh" },
  { title: "A Streetcar Named Desire", year: 1951, director: "Elia Kazan" },
  { title: "Get Out", year: 2017, director: "Jordan Peele" },
  { title: "Stand by Me", year: 1986, director: "Rob Reiner" },
  { title: "Misery", year: 1990, director: "Rob Reiner" },
  { title: "A Bronx Tale", year: 1993, director: "Robert De Niro" },
  { title: "OJ: Made in America", year: 2016, director: "Ezra Edelman" },
  { title: "Saving Private Ryan", year: 1998, director: "Steven Spielberg" },
  { title: "Ghostbusters", year: 1984, director: "Ivan Reitman" },
  { title: "Alien", year: 1979, director: "Ridley Scott" },
  { title: "Aliens", year: 1986, director: "James Cameron" },
  { title: "Jaws", year: 1975, director: "Steven Spielberg" },
  { title: "One Flew Over the Cuckoo's Nest", year: 1975, director: "Miloš Forman" },
  { title: "Die Hard", year: 1988, director: "John McTiernan" },
  { title: "12 Monkeys", year: 1995, director: "Terry Gilliam" },
  { title: "Casino Royale", year: 2006, director: "Martin Campbell" },
  { title: "The Deer Hunter", year: 1978, director: "Michael Cimino" },
  { title: "Roger & Me", year: 1989, director: "Michael Moore" },
  { title: "A River Runs Through It", year: 1992, director: "Robert Redford" },
  { title: "Zodiac", year: 2007, director: "David Fincher" },
  { title: "The Game", year: 1997, director: "David Fincher" },
  { title: "The Social Network", year: 2010, director: "David Fincher" },
  { title: "Inglourious Basterds", year: 2009, director: "Quentin Tarantino" },
  { title: "End of Watch", year: 2012, director: "David Ayer" },
  { title: "Easy Rider", year: 1969, director: "Dennis Hopper" },
  { title: "Bullitt", year: 1968, director: "Peter Yates" },
  { title: "The Graduate", year: 1967, director: "Mike Nichols" },
  { title: "The Firm", year: 1993, director: "Sydney Pollack" },
  { title: "Wall Street", year: 1987, director: "Oliver Stone" },
  { title: "Good Will Hunting", year: 1997, director: "Gus Van Sant" },
  { title: "Wind River", year: 2017, director: "Taylor Sheridan" },
  { title: "The Blues Brothers", year: 1980, director: "John Landis" },
  { title: "Hoosiers", year: 1986, director: "David Anspaugh" },
  { title: "Tommy Boy", year: 1995, director: "Peter Segal" },
  { title: "Bloodsport", year: 1988, director: "Newt Arnold" },
  { title: "Dark Blue", year: 2002, director: "Ron Shelton" },
  { title: "White Men Can't Jump", year: 1992, director: "Ron Shelton" },
  { title: "Chinatown", year: 1974, director: "Roman Polanski" },
  { title: "High Fidelity", year: 2000, director: "Stephen Frears" },
  { title: "The Good, the Bad and the Ugly", year: 1966, director: "Sergio Leone" },
  { title: "Fargo", year: 1996, director: "Joel Coen" },
  { title: "No Country for Old Men", year: 2007, director: "Joel Coen" },
];

const MOVIES = MOVIES_RAW.map((m, i) => ({ ...m, id: i + 1 }));
